config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin, path: Spree.admin_path do
      resources :orders, except: [:show] do
          resources :labels, only: [:new, :create, :show, :update]
      end
  end
end

app/models/spree/label.rb
class Spree::Label < ActiveRecord::Base
    belongs_to :order
    attr_accessor :Enseigne, :ModeCol, :ModeLiv, :NDossier, :Expe_Langage, :Expe_Ad1, :Expe_Ad3, :Expe_Ad4,
                  :Expe_Ville, :Expe_CP, :Expe_Pays, :Expe_Tel1, :Expe_Mail, :Dest_Langage, :Dest_Ad1,
                  :Dest_Ad3, :Dest_Ad4, :Dest_Ville, :Dest_CP, :Dest_Pays, :Dest_Tel1, :Dest_Mail, :NbColis,
                  :CRT_Valeur, :COL_Rel_Pays, :COL_Rel, :LIV_Rel_Pays, :LIV_Rel, :Security, :key
                  
        def concat_label
            "#{self.Enseigne}" + "#{self.ModeCol}" + "#{self.ModeLiv}" + "#{self.NDossier}" +  "#{self.Expe_Langage}" +  
            "#{self.Expe_Ad1}" + "#{self.Expe_Ad3}" + "#{self.Expe_Ad4}" + "#{self.Expe_Ville}" + "#{self.Expe_CP}" + "#{self.Expe_Pays}" + 
            "#{self.Expe_Tel1}" + "#{self.Expe_Mail}" + "#{self.Dest_Langage}" + "#{self.Dest_Ad1}" + "#{self.Dest_Ad3}" + "#{self.Dest_Ad4}" +
            "#{self.Dest_Ville}" + "#{self.Dest_CP}" + "#{self.Dest_Pays}" + "#{self.Dest_Tel1}" + "#{self.Dest_Mail}" + "#{self.weight}" +
            "#{self.NbColis}" + "#{self.CRT_Valeur}" + "#{self.COL_Rel_Pays}" +  "#{self.COL_Rel}" + "#{self.LIV_Rel_Pays}" + "#{self.LIV_Rel}" +
            "#{self.key}"
        end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
    has_many :relais, dependent: :destroy
    has_one :label, dependent: :destroy
    accepts_nested_attributes_for :relais
end

app/models/spree/relai.rb
class Spree::Relai < ActiveRecord::Base
  belongs_to :order
end

app/controllers/spree/admin/labels_controller.rb
class Spree::Admin::LabelsController < Spree::Admin::BaseController
    require 'savon'
    require 'net/http'
    require 'digest/md5'
    before_action :load_order
    
    def show
        @label = Spree::Label.find(params[:id])
    end
    
    def new
        if Spree::Label.exists?(order_id: @order.id)
            @label = Spree::Label.find_by(order_id: @order.id)
        else
            @label = @order.build_label
        end
    end
    
    def create
        @label = @order.build_label(label_params)
        @label.Security = (Digest::MD5.hexdigest(@label.concat_label)).upcase
        client = Savon.client(wsdl: "http://api.mondialrelay.com/Web_Services.asmx?WSDL", logger: Rails.logger,
                              log: true, pretty_print_xml: true)
    
    response = client.call(:wsi2_creation_etiquette, message: { "Enseigne" => @label.Enseigne,
                                    "ModeCol" => @label.ModeCol,
                                    "ModeLiv" => @label.ModeLiv,
                                    "NDossier" => @label.NDossier,
                                    "Expe_Langage" => @label.Expe_Langage,
                                    "Expe_Ad1" => @label.Expe_Ad1,
                                    "Expe_Ad3" => @label.Expe_Ad3,
                                    "Expe_Ad4" => @label.Expe_Ad4,
                                    "Expe_Ville" => @label.Expe_Ville,
                                    "Expe_CP" => @label.Expe_CP,
                                    "Expe_Pays" => @label.Expe_Pays,
                                    "Expe_Tel1" => @label.Expe_Tel1,
                                    "Expe_Mail" => @label.Expe_Mail,
                                    "Dest_Langage" => @label.Dest_Langage,
                                    "Dest_Ad1" => @label.Dest_Ad1,
                                    "Dest_Ad3" => @label.Dest_Ad3,
                                    "Dest_Ad4" => @label.Dest_Ad4,
                                    "Dest_Ville" => @label.Dest_Ville,
                                    "Dest_CP" => @label.Dest_CP,
                                    "Dest_Pays" => @label.Dest_Pays,
                                    "Dest_Tel1" => @label.Dest_Tel1,
                                    "Dest_Mail" => @label.Dest_Mail,
                                    "Poids" => @label.weight,
                                    "NbColis" => @label.NbColis,
                                    "CRT_Valeur" => @label.CRT_Valeur,
                                    "COL_Rel_Pays" => @label.COL_Rel_Pays,
                                    "COL_Rel" => @label.COL_Rel,
                                    "LIV_Rel_Pays" => @label.LIV_Rel_Pays,
                                    "LIV_Rel" => @label.LIV_Rel,
                                    "Security" => @label.Security
                                    })
                                    
    if response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:stat] == "0"
        @label.stat = response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:stat]
        @label.expeditionnum = response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:expedition_num]
        @label.url_etiquette = "http://www.mondialrelay.com" + response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:url_etiquette]
        if @label.save
            redirect_to admin_order_label_path(@order, @label)
        else
            render 'new'
        end
    else
        @label.update_attributes(stat: response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:stat])
        render 'new'
    end
    
    end
    
    def update
        @label = @order.build_label(label_params)
        @label.Security = (Digest::MD5.hexdigest(@label.concat_label)).upcase
        client = Savon.client(wsdl: "http://api.mondialrelay.com/Web_Services.asmx?WSDL", logger: Rails.logger,
                              log: true, pretty_print_xml: true)
    
    response = client.call(:wsi2_creation_etiquette, message: { "Enseigne" => @label.Enseigne,
                                    "ModeCol" => @label.ModeCol,
                                    "ModeLiv" => @label.ModeLiv,
                                    "NDossier" => @label.NDossier,
                                    "Expe_Langage" => @label.Expe_Langage,
                                    "Expe_Ad1" => @label.Expe_Ad1,
                                    "Expe_Ad3" => @label.Expe_Ad3,
                                    "Expe_Ad4" => @label.Expe_Ad4,
                                    "Expe_Ville" => @label.Expe_Ville,
                                    "Expe_CP" => @label.Expe_CP,
                                    "Expe_Pays" => @label.Expe_Pays,
                                    "Expe_Tel1" => @label.Expe_Tel1,
                                    "Expe_Mail" => @label.Expe_Mail,
                                    "Dest_Langage" => @label.Dest_Langage,
                                    "Dest_Ad1" => @label.Dest_Ad1,
                                    "Dest_Ad3" => @label.Dest_Ad3,
                                    "Dest_Ad4" => @label.Dest_Ad4,
                                    "Dest_Ville" => @label.Dest_Ville,
                                    "Dest_CP" => @label.Dest_CP,
                                    "Dest_Pays" => @label.Dest_Pays,
                                    "Dest_Tel1" => @label.Dest_Tel1,
                                    "Dest_Mail" => @label.Dest_Mail,
                                    "Poids" => @label.weight,
                                    "NbColis" => @label.NbColis,
                                    "CRT_Valeur" => @label.CRT_Valeur,
                                    "COL_Rel_Pays" => @label.COL_Rel_Pays,
                                    "COL_Rel" => @label.COL_Rel,
                                    "LIV_Rel_Pays" => @label.LIV_Rel_Pays,
                                    "LIV_Rel" => @label.LIV_Rel,
                                    "Security" => @label.Security
                                    })
                                    
    if response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:stat] == "0"
        @label.stat = response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:stat]
        @label.expeditionnum = response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:expedition_num]
        @label.url_etiquette = "http://www.mondialrelay.com" + response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:url_etiquette]
        if @label.save
            redirect_to admin_order_label_path(@order, @label)
        else
            render 'new'
        end
    else
        @label.update_attributes(stat: response.body[:wsi2_creation_etiquette_response][:wsi2_creation_etiquette_result][:stat])
        render 'new'
    end

    end
    
        private
        
        def load_order
            @order = Spree::Order.friendly.find(params[:order_id])
        end
        
        def label_params
            params.require(:label).permit(:Enseigne, :ModeCol, :ModeLiv, :NDossier, :Expe_Langage, :Expe_Ad1, :Expe_Ad3, :Expe_Ad4,
                  :Expe_Ville, :Expe_CP, :Expe_Pays, :Expe_Tel1, :Expe_Mail, :Dest_Langage, :Dest_Ad1,
                  :Dest_Ad3, :Dest_Ad4, :Dest_Ville, :Dest_CP, :Dest_Pays, :Dest_Tel1, :Dest_Mail, :NbColis,
                  :CRT_Valeur, :COL_Rel_Pays, :COL_Rel, :LIV_Rel_Pays, :LIV_Rel, :weight, :key)
        end
        
        
        
        
        
        
        
     
    
end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do
    
    private
    
    def before_delivery
      return if params[:order].present?

      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
      if Spree::Relai.where(order_id: @order.id).empty?
        @relais = @order.relais.build
      else
        @relais = @order.relais.last
      end
    end
    
    
end

app/views/spree/shared/_label.html.erb
<% if @order.relay? %>
      <li<%== ' class="active"' if current == :print_label %> data-hook='admin_order_tabs_print_label'>
        <%= link_to_with_icon 'wrench', Spree.t(:print_label), new_admin_order_label_path(@order) %>
      </li>
<% end %>

app/views/spree/shared/_mondial.html.erb
    <div id="Zone_Widget"></div>  
    
    <div style="padding:8px; overflow:auto; display:none;">  
        <div style="background:#edffb2; border:solid 1px #a5f913; padding:5px; font-family:verdana; font-size:10px;">  
            <em>Livraison en point relais</em><br/><br/>  
              <%= form.check_box :relay, id: "mondial_checkbox" %>
        </div>  
    </div>
  
    <div id="selectionrelais" style="padding:8px; overflow:auto;">  
        <div style="background:#edffb2; border:solid 1px #a5f913; padding:5px; font-family:verdana; font-size:10px;">  
            <divstyle="vertical-align:top;">  
                <span style="font-weight:bold;text-decoration:underline;">Point Relais sélectionné:</span><br/> 
                <span id="TargetDisplayInfoPR_Widget" /> 
            </div>  
              
            <div style="display:none;">  
                <!-- Les balises suivantes sont utilisées dans la fonction de CallBack pour reçevoir des données à afficher -->  
                <span style="font-weight:bold;text-decoration:underline;">Callback zone</span><br/>  
                <%= form.fields_for :relais, @relais do |relai_fields| %>
                    ID  : <%= relai_fields.text_field :number, id: 'cb_ID' %>
                    Name: <%= relai_fields.text_field :name, id: "cb_Nom" %>
                    Address: <%= relai_fields.text_field :address, id: "cb_Adresse" %>
                    CP: <%= relai_fields.text_field :cp, id: "cb_CP" %>
                    City: <%= relai_fields.text_field :city, id: "cb_Ville" %>
                    Country: <%= relai_fields.text_field :country, id: "cb_Pays" %>
                <% end %> 
            </div>  
        </div>  
    </div>  
            
            <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9QLZdr1ayE-lYNKkQhTmkeO8e5bvmwZM"></script>  
            <script type="text/javascript"> 
            
             
  
            var t;  
  
            // Avec jQuery, exécute le script entre accolades uniquement après le chargement complet de la page  
                $(document).ready(function () {
                // Charge le widget dans la DIV d'id "Zone_Widget" avec les paramètres indiqués 
                 var country = "<%= "#{@order.ship_address.country['iso']}" %>";
                 var postal = "<%= @order.ship_address['zipcode'] %>";
                 $("#Zone_Widget").MR_ParcelShopPicker({  
                    // Target: "#Target_Widget"                                // Selecteur JQuery de l'élément dans lequel sera renvoyé l'ID du Point Relais sélectionné (généralement un champ input hidden)  
                    //, TargetDisplay: "#TargetDisplay_Widget"                // Selecteur JQuery de l'élément dans lequel sera renvoyé l'ID du Point Relais sélectionné (secondaire pour affichage)  
                    TargetDisplayInfoPR: "#TargetDisplayInfoPR_Widget"    // Selecteur JQuery de l'élément dans lequel seront renvoyé les coordonnées complètes de la selection de l'utilisateur  
                    , Brand: "BDTEST  "                                     // Le code client Mondial Relay  
                                                                            // Lorsqu'il est indiqué "BDTEST  ", un message d'avertissement apprait pour avertir que ce sont les paramètres de test qui sont utilisés  
                    , Country: country                                      // Code ISO 2 lettres du pays utilisé pour la recherche  
                    //,AllowedCountries: "FR,ES"                            // Liste des pays selectionnable par l'utilisateur pour la recherche (codes ISO 2 lettres séparés par des virgules)  
                    , PostCode: postal                                      // Code postal pour lancer une recherche par défaut  
                    //,EnableGeolocalisatedSearch: "true"                   // Active ou non la possibilité d'effectuer la recherche sur la position courante lorsque le navigateur de l'utilisateur supporte cette fonction (demande au navigateur)  
                    , ColLivMod: "24R"                                      // Permet de filtrer les Points Relais selon le mode de livraison utilisé (Standard [24R], XL [24L], XXL [24X], Drive [DRI])  
                    //,Weight: ""                                           // Permet de filtrer les Points Relais selon le Poids (en grammes) du colis à livrer  
                    , NbResults: "7"                                       // Nombre de Point Relais à afficher  
                    //,SearchDelay: "3"                                     // Permet de spécifier le nombre de jour entre la recherche et la dépose du colis dans notre réseau  
                    //,SearchFar: ""                                        // Permet de limiter la recherche des Points Relais à une distance maximum  
                    //,CSS: "1"                                             // Permet de spécifier que vous souhaitez utiliser votre propre feuille de style CSS lorsque vous lui donnez la valeur "0"  
                    ,MapScrollWheel: true                                   // Active ou non le zoom on scroll sur la carte des résultats  
                    //,MapStreetView: "false"                               // Active ou non le mode Street View sur la carte des résultats (attention aux quotas imposés par Google)  
                    ,ShowResultsOnMap: true                                 // Active ou non l'affichage des résultats sur une carte  
                    , DisplayMapInfo: true                                  // Active ou non l'affichage d'une popup sur la carte avec les informations du point relais  
                    , OnParcelShopSelected:                                 // Permet l'appel d'une fonction lors de la selection d'un Point Relais  
                        function (data) {                                   // Implémentation de la fonction de traitement, le paramètre Data contient un objet avec les informations du Point Relais  
  
                            // Remplace les données de la balise ayant l'Id "cb_ID" par le contenu html de data.ID  
                            // "data" est le paramètre reçu par la fonction, sont contenu est inconnu à la compilation  
                            // "ID" est contenu dans "data", il pourrait y avoir une erreur si "ID" n'existe pas dans la variable "data" reçue en paramètre  
                            $("#cb_ID").val(data.ID);  
  
                            $("#cb_Nom").val(data.Nom);  
                            $("#cb_Adresse").val(data.Adresse1 + ' ' + data.Adresse2);  
                            $("#cb_CP").val(data.CP);  
                            $("#cb_Ville").val(data.Ville);  
                            $("#cb_Pays").val(data.Pays);  
                            $('#mondial_checkbox').prop('checked', true);
                        }  
                });
                
                
                });
                
                
                
                $('input:radio[name="order[shipments_attributes][0][selected_shipping_rate_id]"]').change(function(){
                var parent = $(this).closest("label");
                var kid = parent.children("span.rate-name").eq(0);
                  if (this.checked && kid.html() == 'Livraison chez votre marchand'){
                    $("#Zone_Widget").children().show();
                    $("#selectionrelais").show();
                 } else {
                    $("#Zone_Widget").children().hide();
                    $('#mondial_checkbox').prop('checked', false);
                    $("#cb_ID").val('');  
                    $("#cb_Nom").val('');  
                    $("#cb_Adresse").val('');  
                    $("#cb_CP").val('');  
                    $("#cb_Ville").val('');  
                    $("#cb_Pays").val('');
                    $("#TargetDisplayInfoPR_Widget").html('');
                    $("#selectionrelais").hide();
                 };
                 });
                 
                $(window).load(function() {
                    var button1 = $('input:radio[name="order[shipments_attributes][0][selected_shipping_rate_id]"]:checked');
                    var parent1 = button1.closest("label");
                    var kid1 = parent1.children("span.rate-name").eq(0);
                    if (kid1.html() != 'Livraison chez votre marchand'){
                        $("#Zone_Widget").children().hide();
                        $("#selectionrelais").hide();
                    };
                     
                    jQuery("#checkout_form_delivery").validate({
                        ignore: "",
                         rules: {
                             "order[relais_attributes][0][number]": {
                                 required: {
                                 depends: function(element){
                                     return $("#Zone_Widget").children(":first").css("display") != 'none';
                                 }
                                 }
                             }
                         },
                         messages: {
                             "order[relais_attributes][0][number]": {
                                 required: "Merci de sélectionner un point relais ou un autre moyen de livraison avant de continuer"
                             }
                         },
                         errorPlacement: function(error, element) {
                            error.prependTo("#methods");
                          }
                     }); 
                });
        </script>  